pipeline {
    agent any
    stages {
        stage('IO - Execute - SAST - ESLint') {
            steps {
                echo 'Download ESLint Adapter & Shell Script'
                sh "curl https://raw.githubusercontent.com/synopsys-sig/io-client-adapters/eslint/eslint/eslint-adapter.json --output eslint-adapter.json"
                sh "curl https://raw.githubusercontent.com/synopsys-sig/io-client-adapters/eslint/eslint/eslint.sh --output eslint.sh"
                synopsysIO() {
                    sh 'io --stage execution --adapters eslint-adapter.json --state io_state.json' }
            }
        }

        post {
            always {
                // Archive Results & Logs
                archiveArtifacts artifacts: '**/*-results*.json', allowEmptyArchive: 'true'
                archiveArtifacts artifacts: '.io/**', allowEmptyArchive: 'true'
                archiveArtifacts artifacts: 'npm-eslint.log', allowEmptyArchive: 'true'

                // Remove the state json file it has sensitive information
                sh 'rm io_state.json'
            }
        }
    }
}
