pipeline {
    agent any
    stages {
        stage('IO - Execute - SAST - GoSec') {
            steps {
                echo 'Download GoSec Adapter & Shell Script'
                sh "curl https://raw.githubusercontent.com/synopsys-sig/io-client-adapters/eslint/gosec/gosec-adapter.json --output gosec-adapter.json"
                sh "curl https://raw.githubusercontent.com/synopsys-sig/io-client-adapters/eslint/gosec/gosec.sh --output gosec.sh"
                synopsysIO() {
                    sh 'io --stage execution --adapters gosec-adapter.json --state io_state.json'
                }
            }
        }

        post {
            always {
                // Archive Results & Logs
                archiveArtifacts artifacts: '**/*-results*.json', allowEmptyArchive: 'true'
                archiveArtifacts artifacts: '.io/**', allowEmptyArchive: 'true'
                archiveArtifacts artifacts: 'gosec-results.json', allowEmptyArchive: 'true'

                // Remove the state json file it has sensitive information
                sh 'rm io_state.json'
            }
        }
    }
}
