pipeline {
    agent any
    stages {
        stage('IO - Execute - SCA - Dependency-Check') { 
            steps {
                echo 'Execute SCA Tool'
                synopsysIO() {
                sh 'io --stage execution --adapters dependency-check-adapter.json --state io_state.json' }
            }
        }

        post {
            always {
                archiveArtifacts artifacts: '**/*-results*.json', allowEmptyArchive: 'true'
                archiveArtifacts artifacts: '**/*-report*.*', allowEmptyArchive: 'true'
                //remove the state json file it has sensitive information
                sh 'rm io_state.json'
            }
        }
    }
}
